# Generated by Django 5.1.4 on 2024-12-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz_App', '0003_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
